### ISSUE TITLE
TypeError: Cannot set property attributes of [object Object] which has only a getter

### ISSUE THREAD

**Issue by dmc1985** [atomiks/tippyjs#417]
I am in the process of writing tests using Enzyme for a React component that I created based on the Tippy component I imported from @tippy.js/react. When I called Enzyme's mount function using the Tooltip component I created with a nested DOM element, I receive the following error: TypeError: Cannot set property attributes of [object Object] which has only a getter.

Here is the code that causes the error: `beforeEach(() => {
        wrapper = mount(
            <Tooltip
                content="content"
                theme="light"
                title="title"
                placement="bottom"
            >
                <div>Test</div>
            </Tooltip>
        );
    })`
However, when I replace `<div>Test</div>` with simple text, it works. 

Any idea of how to resolve this issue? Thanks in advance for your help.

Here is the stack trace: 
at polyfillElementPrototypeProperties (node_modules/tippy.js/dist/tippy.all.js:3379:27)
      at tippy (node_modules/tippy.js/dist/tippy.all.js:4465:5)
      at Function.Object.<anonymous>.tippy.one (node_modules/tippy.js/dist/tippy.all.js:4504:10)
      at Tippy.componentDidMount (node_modules/@tippy.js/react/dist/Tippy.js:141:26)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:14684:22)
      at commitAllLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:15904:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:145:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:36:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:195:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:248:31)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:16074:7)
      at completeRoot (node_modules/react-dom/cjs/react-dom.development.js:17462:3)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:17390:9)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:17294:7)
      at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:17266:3)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:17154:5)
      at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:16948:5)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:17636:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:17663:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:17690:10)
      at ReactRoot.Object.<anonymous>.ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:17956:3)
      at node_modules/react-dom/cjs/react-dom.development.js:18096:14
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:17517:10)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:18092:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:18151:12)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:314:114)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:119:16)
      at mount (node_modules/enzyme/build/mount.js:21:10)
      at Object.test (src/components/Card/__tests__/Card.test.js:9:44)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by dmc1985** [comment]
My apologies, I opened this issue on the tippyjs-react github page and closed it here.
